apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: gitops
images:
- name: nginx
  newName: sumitroopchandani/nginx
  newTag: latest
- name: npm
  newName: sumitroopchandani/hello-gitops
  newTag: "18"
